spring.application.name=polls-backend
spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:3306/polls?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=asdf1234
spring.jpa.hibernate.ddl-auto=update
spring.web.error.include-message=always
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
